### ISSUE TITLE
Can you support PHPSpec?

### ISSUE THREAD

**Issue by CMCDragonkai** [SaschaGalley/grunt-phpunit#8]
Seems like the wrong place to ask, but since you built one for phpunit, would it be easy (easier) to support PHPspec as a grunt task too?

**Comment by jrcryer** [comment]
Just started a new repo for it:

https://github.com/jrcryer/grunt-phpspec

Shouldn't take too long to pull together.  Any particular usage you need? 

Cheers,

James

**Comment by jrcryer** [comment]
Hi,

I've added a new plugin for PHPSpec: https://npmjs.org/package/grunt-phpspec

Probably worth raising issues in it's respective repo.

Cheers,

James

**Comment by CMCDragonkai** [comment]
Awesome thanks!

On 29/05/2013 3:41 AM, James Cryer wrote:

> Hi,
> 
> I've added a new plugin for PHPSpec: 
> https://npmjs.org/package/grunt-phpspec
> 
> Probably worth raising issues in it's respective repo.
> 
> Cheers,
> 
> James
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/SaschaGalley/grunt-phpunit/issues/8#issuecomment-18567169.

## 

Founder of Polycademy & Code for Australia
http://polycademy.com
